apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observatorium

vars:
- fieldref:
    fieldPath: metadata.namespace
  name: NAMESPACE
  objref:
    apiVersion: integreatly.org/v1alpha1
    kind: Grafana
    name: grafana

resources:
- grafana-grafana.yaml
- grafana-k8s-proxy-secret.yaml
- grafana-proxy-clusterrolebinding.yaml
- grafana-proxy-clusterrole.yaml
- ocp-injected-certs-cm.yaml

configurations:
- kustomizeconfig/configuration.yaml
