apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observatorium

configMapGenerator:
- files:
  - prometheus_stats.json=conf/prometheus_2_stats.json
  name: prometheus-stats-dashboard

vars:
- fieldref:
    fieldPath: metadata.namespace
  name: NAMESPACE
  objref:
    apiVersion: integreatly.org/v1alpha1
    kind: Grafana
    name: grafana

resources:
- grafana-grafana.yaml
- grafana-k8s-proxy-secret.yaml
- grafana-proxy-clusterrolebinding.yaml
- grafana-proxy-clusterrole.yaml
- ocp-injected-certs-cm.yaml
- prometheus-grafanadatasource.yaml
- prometheus-grafanadashboard.yaml

configurations:
- kustomizeconfig.yaml
