apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observatorium

secretGenerator:
- files:
  # REPLACE
  - tls.crt=conf/prometheus.crt.pem
  - tls.key=conf/prometheus.key.pem
  name: prometheus-client-certs
  options:
    disableNameSuffixHash: true
- files:
  # REPLACE
  - ca.crt=conf/observatorium-api.ca.crt.pem
  name: observatorium-api-server-certs
  options:
    disableNameSuffixHash: true
- files:
  - prometheus-additional-scrape-configs.yaml=conf/prometheus-additional-scrape-configs.yaml
  name: prometheus-additional-scrape-configs

resources:
- prometheus-prometheus.yaml

configurations:
- kustomizeconfig/configuration.yaml
